[package]
name = "easytls"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
humantime = "2.2.0"
rcgen = { version = "0.13", features = ["pem", "x509-parser"] }
time = "0.3.41"
